//
//  RecipeCollectiosn.swift
//  TabbarPages
//
//  Created by Wenqi Wang on 06/04/2017.
//  Copyright © 2017 SixSix. All rights reserved.
//

import UIKit
<<<<<<< HEAD

// all preperations for all recipes, preperation video stored on Firebase Storage

=======
 // these are the hard coded preparations
>>>>>>> 8555f0390bfc1d0eafa0257a0310da3cec0174a7
var beatEggs = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fbeategg.mp4?alt=media&token=b8d496ff-8aac-4468-9bdc-b1db02f94529".data(using: .utf8)!, encoding: .utf8)!, prepTime: 10, desc: "BEAT eggs, milk and nutmeg in shallow dish until blended.", imageName: "beategg")

var sliceBeef = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fbeef.mp4?alt=media&token=6d1b451b-729d-4284-ad4b-e209474e4075".data(using: .utf8)!, encoding: .utf8)!, prepTime: 5, desc: "slice beef into thin strips.", imageName: "beef")

var peelCarrot = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fcarrot.mp4?alt=media&token=d374c3e4-d110-4884-a172-e860441fb3ea".data(using: .utf8)!, encoding: .utf8)!, prepTime: 2, desc: "peel carrots nicely, and cut them into prices", imageName: "carrot")

var chopOnion = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fcutonion.mp4?alt=media&token=9e488c99-e1e5-4ece-8d85-6437e11fd2ab".data(using: .utf8)!, encoding: .utf8)!, prepTime: 2, desc: "chop onion nicely", imageName: "cutonion")

var cutPotato = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fcutpotato.mp4?alt=media&token=b2c41cef-0a21-472f-8199-788f6e72fb1e".data(using: .utf8)!, encoding: .utf8)!, prepTime: 3, desc: "peel the potatos, and cut them into pieces", imageName: "cutpotato")

var peelPinapple = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fpinnapple.mp4?alt=media&token=52ec4c42-34ad-43f3-b5df-91ea525c6b98".data(using: .utf8)!, encoding: .utf8)!, prepTime: 5, desc: "peel and cut the pineapple", imageName: "pinnapple")

var chopBeans = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fbeans.mp4?alt=media&token=49400cb8-7854-469c-84c8-07b9e055fa4f".data(using: .utf8)!, encoding: .utf8)!, prepTime: 2, desc: "wash and cut the green beans", imageName: "beans")

var peelsalmon = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fpeelsalmon.mp4?alt=media&token=c2f90158-c5ac-4acd-bb88-a0ff178d882a".data(using: .utf8)!, encoding: .utf8)!, prepTime: 5, desc: "take the skin off a salmon", imageName: "peelsalmon")

var trimBroccoli = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fcutbroccoli.mp4?alt=media&token=4ac4ea11-3a0e-4911-b413-556e90c8c364".data(using: .utf8)!, encoding: .utf8)!, prepTime: 3, desc: "trim broccoli rabe", imageName: "cutbroccoli")

var cutchicken = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fcutchicken.mp4?alt=media&token=dc7e16e0-8a90-431e-89d0-54452d88dbb6".data(using: .utf8)!, encoding: .utf8)!, prepTime: 5, desc: "slice chicken into chunks", imageName: "cutchicken")

var trimrib = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Ftrimrib.mp4?alt=media&token=e8c9d329-be8a-4935-b218-b763320a5792".data(using: .utf8)!, encoding: .utf8)!, prepTime: 10, desc: "trim the rib", imageName: "trimrib")

var bun = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fbuns.mp4?alt=media&token=be990270-7136-4e4e-8196-4e42b5f78233".data(using: .utf8)!, encoding: .utf8)!, prepTime: 40, desc: "make the dough for buns", imageName: "bun")

var cutGarlic = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fvideoplayback.mp4?alt=media&token=8914e670-7b1d-412f-acf5-f20a2672773d".data(using: .utf8)!, encoding: .utf8)!, prepTime: 2, desc: "Mash Garlic In Seconds", imageName: "Garlic")

var chopCabbage = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fvideoplayback2.mp4?alt=media&token=3f2b98a2-26aa-4c50-857e-3abcce610eaf".data(using: .utf8)!, encoding: .utf8)!, prepTime: 3, desc: "Cut Up a Cabbage", imageName: "Garlic")

var chopMashroom = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fmushroom.mp4?alt=media&token=ef46410c-652a-4837-819c-dcc1e09557ff".data(using: .utf8)!, encoding: .utf8)!, prepTime: 2, desc: "How To Slice Mushrooms", imageName: "Garlic")

var cookpastry = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fpuff.mp4?alt=media&token=57bb9d51-eae8-4332-9ba6-ed1502192b75".data(using: .utf8)!, encoding: .utf8)!, prepTime: 5, desc: "Cook puff pastry using frozen pastry", imageName: "Garlic")

var cutcelery = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fcutcelery.mp4?alt=media&token=31784623-2037-4252-8c57-e5e4685da31f".data(using: .utf8)!, encoding: .utf8)!, prepTime: 2, desc: "Chop the celery to small pieces", imageName: "Garlic")

var cutpepper = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fgreenbellpepper.mp4?alt=media&token=00751b78-7602-4834-82fd-a0da3b67cc60".data(using: .utf8)!, encoding: .utf8)!, prepTime: 1, desc: "Chop the bell pepper to small pieces", imageName: "Garlic")

var cutSausage = Preparation(url: String(data: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/video%2Fsausage.mp4?alt=media&token=e1b39df2-c7f5-4cd4-ac9b-d9c3da64a9a9".data(using: .utf8)!, encoding: .utf8)!, prepTime: 2, desc: "How to Cut Sausage for a Meat", imageName: "Garlic")

var recipeArray = [Recipe]()

<<<<<<< HEAD
// all availablec recipes, images stored on firebase storage
=======
//these are the hard coded recipe steps
>>>>>>> 8555f0390bfc1d0eafa0257a0310da3cec0174a7

let frenchToastRecipe = Recipe(id: 1, name: "FRENCH TOAST", category: "european", preparationArray: [beatEggs], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/frenchToastRecipe%2FfrenchtoastImage.jpg?alt=media&token=eb633427-b602-4d9b-a533-5fb320467b36", price: 4, cookTime: 5, tag: ["vegetarian",  "breakfast", "toast", "french"], ingredients: ["EGGS" : ["8", "pieces"], "MILK" : ["0.75", "cup"], "day-old bread" : ["8", "slices"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/frenchToastRecipe%2Fheat.jpg?alt=media&token=855e741f-a148-4930-9062-efa3f7030a74", "HEAT lightly greased large nonstick skillet over high heat until hot."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/frenchToastRecipe%2FplaceF.jpg?alt=media&token=4b3b6abd-a72d-4536-aef2-091136accf07", "PLACE as many bread slices in hot pan as will fit in single layer. Immediately reduce heat to medium." ], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/frenchToastRecipe%2FcookF.jpg?alt=media&token=216194b5-7759-4a44-8db9-2fe7c6541b40", "COOK until golden brown and no visible liquid egg remains, 2 to 3 minutes per side. REPEAT to cook remaining bread. SERVE immediately."]], details: "French toast, also known as eggy bread, Bombay toast, German toast, gypsy toast, poor knights, or Spanish toast, is a dish made of bread soaked in milk, then in beaten eggs and then fried.")

let scrambledEggsRecipe = Recipe(id: 2, name: "SCRAMBLED EGGS", category: "traditional", preparationArray: [beatEggs], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/scrambledEggsRecipe%2FscrambledImage.jpg?alt=media&token=11030620-57d9-43ac-9305-4411d16512b8", price: 3, cookTime: 3, tag: ["breakfast", "eggs", "american"], ingredients: ["EGGS" : ["4", "pieces"], "MILK" : ["0.25", "cup"], "butter" : ["2", "tsp"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/scrambledEggsRecipe%2FheatS.jpg?alt=media&token=3f92f4e4-4ecc-458f-9ff4-d6e4a0cf1930", "HEAT butter in large nonstick skillet over medium heat until hot."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/scrambledEggsRecipe%2FcookS.jpg?alt=media&token=0a74a4f5-1aea-4596-8195-6c5d4adaa698", "POUR IN egg mixture. As eggs begin to set, GENTLY PULL the eggs across the pan with a spatula, forming large soft curds." ], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/scrambledEggsRecipe%2FcookS.jpg?alt=media&token=0a74a4f5-1aea-4596-8195-6c5d4adaa698", "CONTINUE cooking – pulling, lifting and folding eggs – until thickened and no visible liquid egg remains. Do not stir constantly. REMOVE from heat."]], details: "Scrambled eggs is a dish made from whites and yolks of eggs stirred or beaten together in a pan while being gently heated, typically with salt and butter and variable other ingredients.")

let flatPizzaRecipe = Recipe(id: 3, name: "FLATBREAD PIZZA", category: "european", preparationArray: [beatEggs], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/flatPizzaRecipe%2FflatpizzaImage.jpg?alt=media&token=ab42ef6e-a73c-4566-a714-39e071ff74bf", price: 4, cookTime: 3, tag: ["breakfast", "pizza", "Italian"], ingredients: ["EGGS" : ["1", "pieces"], "MILK" : ["1", "tbsp"], "breakfast sausage crumbles" : ["2", "tbsp"], "round flatbread (6-inch)": ["1", "piece"], "Cheddar cheese": ["2", "tbsp"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/flatPizzaRecipe%2FcoatM.jpg?alt=media&token=037ae0d9-3a93-49bd-ba75-23de0047dcc1", "COAT in 2-cup microwave-safe cereal bowl with cooking spray. ADD egg and milk; BEAT until blended. ADD sausage."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/flatPizzaRecipe%2FcookM.jpg?alt=media&token=d91e3909-b775-484c-8da4-57fffbb04dad", "MICROWAVE on HIGH 30 seconds; push cooked edges toward center. MICROWAVE until egg is almost set, about 15 to 45 seconds longer." ]], details: "pizza made with mozzarella, tomatoes, basil & garlic is called Margherita, although a combination of tomato, mozzarella & basil is called caprese.")

let asianBeefRecipe = Recipe(id: 4, name: "ASIAN BEEF", category: "asian fusion", preparationArray: [sliceBeef, chopOnion], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/asianBeefRecipe%2FasianbeefImage.jpg?alt=media&token=4e6d4b51-39ef-4292-bf4f-65ef579d9ee2", price: 8, cookTime: 15, tag: ["low fat", "beef", "asian", "dinner", "lunch"], ingredients: ["SOY SAUCE" : ["2", "tbsp"], "BROWN SUGAR" : ["1", "tbsp"], "minced fresh ginger root" : ["1", "tbsp"], "snow peas": ["8", "ounces"], "Cheddar cheese": ["2", "tbsp"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/asianBeefRecipe%2FcoatM.jpg?alt=media&token=4d6d9949-39e5-4d7c-8289-26a39123175f", "COAT in 2-cup microwave-safe cereal bowl with cooking spray. ADD egg and milk; BEAT until blended. ADD sausage."],["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/asianBeefRecipe%2Fcookbeef.jpg?alt=media&token=91983e9e-c442-445f-97fd-f427c1e3fac4", "Heat oil in a wok or skillet over medium high heat. Stir-fry ginger and garlic for 30 seconds. Add the steak and stir-fry for 2 minutes or until evenly browned. Add the snow peas and stir-fry for an additional 3 minutes." ]], details: "Stir-fried beef in a light gingery sauce. Serve over steamed rice or hot egg noodles.")

let balsamicGlazedCarrots = Recipe(id: 5, name: "Balsamic Glazed Carrots", category: "traditional", preparationArray: [peelCarrot], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/balsamicGlazedCarrots%2Fglazecarrot.jpg?alt=media&token=ee1b8cf0-21bd-42bf-94ea-3c698d069b82", price: 8, cookTime: 45, tag: ["low fat", "beef", "asian", "dinner", "lunch", "vegetarian"], ingredients: ["SOY SAUCE" : ["2", "tbsp"], "BROWN SUGAR" : ["1", "tbsp"], "minced fresh ginger root" : ["1", "tbsp"], "snow peas": ["8", "ounces"], "Cheddar cheese": ["2", "tbsp"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/balsamicGlazedCarrots%2FcoatM.jpg?alt=media&token=2b99a3dd-3c6b-4309-bfa4-2ac3282cebfe", "Preheat oven to 350°. On a large baking sheet, drizzle carrots with oil, then season with salt and pepper. Toss until combined and bake until carrots are tender, 38 to 40 minutes."],["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/balsamicGlazedCarrots%2FstirsauceImage.jpg?alt=media&token=ebde2cb1-3a28-474c-9319-efc40b343a37", "Meanwhile, make balsamic glaze: In a small saucepan, combine balsamic vinegar and honey. Simmer until reduced by half, stirring occasionally, 15 minutes (the mixture should coat the back of a spoon). Let cool slightly."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/balsamicGlazedCarrots%2FpoursauceImage.jpg?alt=media&token=979190d8-466e-4d96-97a8-23e855451b72", "Drizzle carrots with balsamic glaze and garnish with parsley. Serve warm."]], details: "Drain and transfer to a bowl. Melt butter in the same saucepan; stir brown sugar, salt, and white pepper into butter until brown sugar and salt have dissolved. Transfer carrots into brown sugar sauce; cook and stir until carrots are glazed with sauce, about 5 more minutes.")

let greenBeanandPotatoSalad = Recipe(id: 6, name: "Green Bean and Potato Salad", category: "asian fusion", preparationArray: [cutPotato, chopOnion], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greenBeanandPotatoSalad%2FgreenBeanandPotatoImage.jpg?alt=media&token=0f6cd068-2ba2-4fd4-8a0e-9cde588d8e2d", price: 5, cookTime: 20, tag: ["low fat", "vegetarian", "lunch"], ingredients: ["red potatoes" : ["2", "pounds"], "fresh green beans" : ["1", "pound"], " chopped fresh basil" : ["1", "cup"], "small red onion": ["1", "piece"], " clove garlic": ["1", "piece"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greenBeanandPotatoSalad%2FcoatM.jpg?alt=media&token=8770dc57-d9b1-48bd-91ad-e7e70c2fb72e", "Preheat oven to 350°. On a large baking sheet, drizzle carrots with oil, then season with salt and pepper. Toss until combined and bake until carrots are tender, 38 to 40 minutes."],["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greenBeanandPotatoSalad%2FboilpotatoImage.jpg?alt=media&token=d77113c1-80ff-46d0-a009-57d6dc1cbc08", "Place the potatoes in a large pot, and fill with about 1 inch of water. Bring to a boil, and cook for about 15 minutes, or until potatoes are tender. Throw in the green beans to steam after the first 10 minutes. Drain, cool, and cut potatoes into quarters. Transfer to a large bowl, and toss with fresh basil, red onion, salt and pepper. Set aside."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greenBeanandPotatoSalad%2FsaladDressing.jpg?alt=media&token=cff030da-ab18-49fc-b6a2-8fa6470ba67d", "In a medium bowl, whisk together the balsamic vinegar, mustard, lemon juice, garlic, Worcestershire sauce and olive oil. Pour over the salad, and stir to coat. Taste and season with additional salt and pepper if needed."]], details: "This is awesome! This salad will stay for several days, and improves in flavor. It may be served chilled or room temperature. Preparation time includes cooking the potatoes and beans.")

let mangoSalsaonTilapiaFillets = Recipe(id: 7, name: "Mango Salsa on Tilapia Fillets",category: "traditional", preparationArray: [peelPinapple], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/mangoSalsaonTilapiaFillets%2Fmangofillet.jpg?alt=media&token=5b84f87e-fffd-4209-b20d-9bbd88ec4620", price: 12, cookTime: 25, tag: ["low fat", "seafood", "dinner"], ingredients: ["fresh pineapple" : ["1", "pounds"], "strawberries" : ["1", "pound"], " large mango" : ["1", "cup"], "tilapia fillets": ["2", "pounds"], " clove garlic": ["1", "piece"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/mangoSalsaonTilapiaFillets%2FtossfruitImage.jpg?alt=media&token=8ed925c3-dffd-488e-bcb8-c4ce94553db4", "In a bowl, toss together the pineapple, strawberries, kiwifruit, mango, tomatoes, cilantro, and balsamic vinegar."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/mangoSalsaonTilapiaFillets%2FpanfryingtilapiaImage.jpg?alt=media&token=d34d049c-5cf1-4e79-a016-a536e11e16f9", "Spray a skillet with cooking spray, and heat over medium-high heat. Sprinkle tilapia fillets with seasoned pepper blend, and pan-fry until fish turns white and opaque, 2 to 3 minutes per side. Serve fish topped with salsa."]], details: "Delicious dish with great balance of protain and fruits")

let sesameGreenBeans = Recipe(id: 8, name: "Sesame Green Beans",category: "asian fusion", preparationArray: [chopBeans], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/sesameGreenBeans%2Fgreenbean.jpg?alt=media&token=d54642f2-a56a-47fd-a210-426f4f990e46", price: 6, cookTime: 15, tag: ["low fat", "vegetarian", "lunch", "dinner"], ingredients: ["sesame seeds" : ["1", "tbsp"], "chicken broth" : ["1", "cup"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/sesameGreenBeans%2Fheat.jpg?alt=media&token=987f8ace-85a2-4b52-b438-ef5d4938e45b", "Heat oil in a large skillet or wok over medium heat. Add sesame seeds. When seeds start to darken, stir in green beans. Cook, stirring, until the beans turn bright green."],["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/sesameGreenBeans%2Fstirfrybeans.jpg?alt=media&token=d641e4a6-25f1-48ee-8a18-423426e10c6d", "Pour in chicken broth, salt and pepper. Cover and cook until beans are tender-crisp, about 10 minutes. Uncover and cook until liquid evaporates."]], details: "For such a simple dish, you will be surprised at how much flavor this has! Broccoli is equally delicious prepared this way.")

let cedarPlankedSalmon = Recipe(id: 9, name: "Cedar Planked Salmon",category: "traditional", preparationArray: [peelsalmon], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cedarPlankedSalmon%2FsalmonImage.jpg?alt=media&token=983a9504-01cc-4426-85de-c65f8dfee060", price: 15, cookTime: 20, tag: ["low fat", "seafood", "lunch", "dinner"], ingredients: ["green onions" : ["1", "pieces"], "salmon fillets, skin removed" : ["2", "pounds"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cedarPlankedSalmon%2FsoakPlank.jpg?alt=media&token=15d778c3-c0b6-4284-9d8e-002b9d658ff7", "Soak the cedar planks for at least 1 hour in warm water. Soak longer if you have time."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cedarPlankedSalmon%2Fsoaksalmonimage.jpg?alt=media&token=f0fbabe0-9408-43f8-be6a-7bca728114d2", "In a shallow dish, stir together the vegetable oil, rice vinegar, sesame oil, soy sauce, green onions, ginger, and garlic. Place the salmon fillets in the marinade and turn to coat. Cover and marinate for at least 15 minutes, or up to one hour."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cedarPlankedSalmon%2FgrillsalmonImage.jpg?alt=media&token=e5a91394-c93c-4d31-8bc9-1ca6facc14f0", "Place the salmon fillets onto the planks and discard the marinade. Cover, and grill for about 20 minutes. Fish is done when you can flake it with a fork. It will continue to cook after you remove it from the grill."]], details: "Where this recipe calls for lemon zest and rosemary, the native Coast Salish Indians on Vancouver Island would use grand-fir needles. Either way, the salmon takes on a light, smoky woodiness from grilling on a cedar plank, for a lovely pairing of earth and ocean.")

let broccoli = Recipe(id: 9, name: "Broccoli Rabe with Roasted Peppers",category: "traditional", preparationArray: [trimBroccoli], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/brocolli%2Fbrocolli.jpg?alt=media&token=844f08ae-81bf-4cdc-a7e1-83533f7c3981", price: 5, cookTime: 10, tag: ["low fat", "vegetarian", "lunch", "dinner"], ingredients: ["cloves garlic" : ["5", "pieces"], "bunch broccoli rabe" : ["1", "piece"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/brocolli%2Fboilbroc.jpg?alt=media&token=8d289047-2d8d-4dfe-9e11-a9236c702bba", "Bring a large pot of lightly salted water to a boil. Add the broccoli rabe, and cook uncovered until the stems are tender, about 5 minutes. Drain in a colander."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/brocolli%2Fheat.jpg?alt=media&token=070156df-4b3e-4318-a6b8-d1dab9f3639b", "Heat the olive oil in a large skillet over medium heat. Stir in the garlic, and cook until tender, about 1 minute."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/brocolli%2FstirbroImage.jpg?alt=media&token=e631b61b-cf71-4e3a-ae09-ecef6a13a5ff", "Add the broccoli rabe. Cook and stir until the broccoli rabe has been cooked to your desired degree of tenderness, about 5 minutes for soft. Stir in the roasted peppers until heated, then remove the skillet from the heat, and stir in the lemon juice. Sprinkle with Parmesan cheese to serve."]], details: "Orecchiette with broccoli rabe, also known as rapini, is a classic dish from Apulia, the region of Italy that makes up the heel of the country’s boot shape. To make the dish more colorful, I added red bell pepper to the traditional mix. The sweetness of the peppers makes a nice contrast to the bitter greens.")

let kungpao = Recipe(id: 10, name: "Kung Pao Chicken", category: "asian fusion", preparationArray: [cutchicken], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/kungpao%2Fkungpao.jpg?alt=media&token=5b86b8f4-4aa4-4ec9-b8af-d0108a4b90f2", price: 10, cookTime: 15, tag: ["low fat", "lunch", "dinner"], ingredients: ["peanuts" : ["4", "ounce"], "chickenbreast": ["1", "pounds"], "green onions": ["4", "piece"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/kungpao%2Fmarinade.jpg?alt=media&token=b9fb3ed8-d879-4742-be44-23324c717d3b", "Combine 1 tablespoon wine, 1 tablespoon soy sauce, 1 tablespoon oil and 1 tablespoon cornstarch/water mixture and mix together. Place chicken pieces in a glass dish or bowl and add marinade. Toss to coat. Cover dish and place in refrigerator for about 30 minutes."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/kungpao%2Fsauce.png?alt=media&token=da3bc836-eae0-4be0-bd13-823fa7c3f533", " In a small bowl combine 1 tablespoon wine, 1 tablespoon soy sauce, 1 tablespoon oil, 1 tablespoon cornstarch/water mixture, chili paste, vinegar and sugar. Mix together and add green onion, garlic, water chestnuts and peanuts. In a medium skillet, heat sauce slowly until aromatic."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/kungpao%2Fmix.jpg?alt=media&token=c09e6ced-5b80-4e03-b65e-aac1f708172f", "Meanwhile, remove chicken from marinade and saute in a large skillet until meat is white and juices run clear. When sauce is aromatic, add sauteed chicken to it and let simmer together until sauce thickens."]], details: "Spicy chicken with peanuts, similar to what is served in Chinese restaurants. It is easy to make, and you can be as sloppy with the measurements as you want. They reduce to a nice, thick sauce. Substitute cashews for peanuts, or bamboo shoots for the water chestnuts. You can't go wrong! Enjoy!")

let spareribs = Recipe(id: 11, name: "Chinese Spareribs", category: "asian fusion", preparationArray: [trimrib], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/spareribs%2Frib.jpg?alt=media&token=dbfc9ca2-b261-4f07-af78-eb20288551fe", price: 15, cookTime: 75, tag: ["lunch", "dinner"], ingredients: ["pork spareribs": ["1", "pounds"], "honey": ["1", "bottle"], "sake": ["1", "bottle"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/spareribs%2Fpreprib.jpg?alt=media&token=67a729bd-359f-4152-9f66-af592f5fb324", "In a shallow glass dish, mix together the hoisin sauce, ketchup, honey, soy sauce, sake, rice vinegar, lemon juice, ginger, garlic and five-spice powder. Place the ribs in the dish, and turn to coat. Cover and marinate in the refrigerator for 2 hours, or as long as overnight."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/spareribs%2Fheatoven.jpg?alt=media&token=3efdf668-4c29-463c-9293-775a18466fc7", "Preheat the oven to 325 degrees F (165 degrees C). Fill a broiler tray with enough water to cover the bottom. Place the grate or rack over the tray. Arrange the ribs on the grate."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/spareribs%2Finoven.jpg?alt=media&token=e4fb404a-7324-4dda-a7e6-dfd8a6f344e1", "Place the broiler rack in the center of the oven. Cook for 40 minutes, turning and brushing with the marinade every 10 minutes. Let the marinade cook on for the final 10 minutes to make a glaze. Finish under the broiler if desired. Discard any remaining marinade."]], details: " This recipe is pretty simple, and yields tender, juicy, tangy ribs. In Japan, I cooked this in the fish broiler, but it should be fine on the grill or in the oven." )

let buns = Recipe(id: 12, name: "Chinese Steamed Buns", category: "asian fusion", preparationArray: [bun], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/buns%2Fsteambun.jpg?alt=media&token=41f228a8-0919-476a-ad8f-a1bd2ad5cfcc", price: 10, cookTime: 75, tag: ["breakfast", "lunch", "dinner"], ingredients: ["All-Purpose Flour" : ["1", "pounds"], "active dry yeast": ["1", "ounce"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/buns%2Fflour.jpg?alt=media&token=053e320b-289b-45c8-8e16-86c776600071", "Mix together yeast, 1 teaspoon sugar, 1/4 cup flour, and 1/4 cup warm water. Allow to stand for 30 minutes"], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/buns%2Fmake.jpg?alt=media&token=7505b92c-fee6-455f-8816-908e565d73ba", "Punch down dough, and spread out on a floured board. Sprinkle baking powder evenly on surface, and knead for 5 minutes. Divide dough into 2 parts, and place the piece you are not working with in a covered bowl. Divide each half into 12 parts. Shape each part into a ball with smooth surface up. Put each ball on a wax paper square. Let stand covered until double, about 30 minutes."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/buns%2Fsteam.jpg?alt=media&token=76bcbc20-6978-4103-b359-88b336a10d1d", "Bring water to a boil in wok, and reduce heat to medium; the water should still be boiling. Place steam-plate on a small wire rack in the middle of the wok. Transfer as many buns on wax paper as will comfortably fit onto steam-plate leaving 1 to 2 inches between the buns. At least 2 inches space should be left between steam-plate and the wok. Cover wok with lid. Steam buns over boiling water for 15 minutes."]], details: "Here's some yummy, Chinese dim sum you can make, either plain without meat fillings, or with meat fillings. A wok equipped with a stainless steel steam plate, a plate with holes to allow steam to pass, is required to make these tasty buns. You may use milk in place of the warm water if you wish.")

let chickenThigh = Recipe (id: 13, name: "Honey-Garlic Slow Cooker Chicken Thighs", category: "traditional", preparationArray: [cutGarlic, cutchicken, chopOnion], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/chickenThigh%2FchickenThigh.jpg?alt=media&token=122f0739-7c66-4f00-9a39-d6454c9ddae9", price: 12, cookTime: 300, tag: ["lunch", "dinner"], ingredients: ["Chicken Thighs" : ["1", "pound"], "honey": ["1", "tablespoon"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/chickenThigh%2Fchickenthigh2.jpg?alt=media&token=e66d8bde-59e4-4305-bfd6-2ec43dcc1a4d", "Whisk soy sauce, ketchup, honey, garlic, and basil together in a bowl; pour over the chicken."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/chickenThigh%2FchickenThigh.jpg?alt=media&token=122f0739-7c66-4f00-9a39-d6454c9ddae9", "Cook on Low for 6 hours."]], details: "It's easy and uses pantry staples. Always a hit with adults and kids. Serve with basmati rice or quinoa and steamed or roasted vegetables.")


let chineseRib = Recipe (id: 14, name: "Chinese Spareribs", category: "asian fusion", preparationArray: [cutGarlic, trimrib, chopOnion, chopBeans], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/ChineseRib%2FChineseRib.jpg?alt=media&token=5eabddba-9ed2-458c-8fee-4f260161c678", price: 13, cookTime: 45, tag: ["lunch", "dinner"], ingredients: ["Pork Spareribs" : ["1", "pound"], "ketchup": ["1", "tablespoon"], "honey": ["1", "tablespoon"], "soy sauce": ["1", "tablespoon"], "Chinese five spice powder": ["1/4", "tsp"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/ChineseRib%2FChineseRib1.jpg?alt=media&token=cb378ef9-e4bb-426b-8160-c167839136d4", "In a shallow glass dish, mix together the hoisin sauce, ketchup, honey, soy sauce, sake, rice vinegar, lemon juice, ginger, garlic and five-spice powder. Place the ribs in the dish, and turn to coat. Cover and marinate in the refrigerator for 2 hours, or as long as overnight."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/ChineseRib%2FChineseRib2.jpg?alt=media&token=e9e0844e-658c-415c-993a-196625735978", "Preheat the oven to 325 degrees F (165 degrees C). Fill a broiler tray with enough water to cover the bottom. Place the grate or rack over the tray. Arrange the ribs on the grate."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/ChineseRib%2FChineseRib3.jpg?alt=media&token=7f19366f-6831-42cf-8cce-dd1baa80e780", "Place the broiler rack in the center of the oven. Cook for 40 minutes, turning and brushing with the marinade every 10 minutes. Let the marinade cook on for the final 10 minutes to make a glaze. Finish under the broiler if desired. Discard any remaining marinade."]], details: "This recipe is pretty simple, and yields tender, juicy, tangy ribs. In Japan, this cooked in the fish broiler, but it should be fine on the grill or in the oven.")


let cabbageFat = Recipe (id: 15, name: "Cabbage Fat-Burning Soup", category: "traditional", preparationArray: [cutGarlic, peelCarrot, chopOnion, cutPotato, chopCabbage], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/vegeSoup%2Fsoup.jpg?alt=media&token=54e2f256-e5dd-4dc2-a6c7-791f0c8aa944", price: 6, cookTime: 15, tag: ["lunch", "dinner", "low fat", "breakfast", "vegetarian"], ingredients: ["potatoes" : ["16", "ounces"], "onions": ["3", " pieces"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/vegeSoup%2Fsoup1.jpg?alt=media&token=587e731c-981a-4ad3-98c9-24adc401bfa3", "Place carrots, onions, tomatoes, cabbage, green beans, peppers, and celery in a large pot. Add onion soup mix, tomato juice, beef broth, and enough water to cover vegetables. Simmer until vegetables are tender. May be stored in the refrigerator for several days."]], details: "This tomato and cabbage soup was rumored, in days of old, to melt away those thighs.")

let VegeBibimbap = Recipe (id: 16, name: "Vegetarian Bibimbap", category: "asian fusion", preparationArray: [cutGarlic, beatEggs, chopOnion, peelCarrot, chopMashroom, chopBeans, chopCabbage], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/vegerice%2Fvegebi.jpg?alt=media&token=5e4de84a-ccf6-483d-a628-c57b5f02a2c1", price: 11, cookTime: 20, tag: ["lunch", "dinner","low fat", "vegetarian"], ingredients: ["Mushrooms" : ["4.5", "ounces"], "carrots": ["1", "piece"], "cabbage": ["1", "piece"], "soy sauce":["2", "tablespoons"], "eggs":["3", "pieces"], "sesame oil":["2","tablespoons"], "rice": ["2", "cups"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/vegerice%2Fvege1.jpg?alt=media&token=a476c527-7240-4082-a182-6e6ee365c419", "Heat sesame oil in a large skillet over medium heat; cook and stir carrot and zucchini in the hot oil until vegetables begin to soften, about 5 minutes. Stir in bean sprouts, bamboo shoots, and mushrooms. Cook and stir until carrots are tender, about 5 more minutes. Season to taste with salt and set vegetables aside."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/vegerice%2Fvege2.jpg?alt=media&token=09db56df-64a9-47ba-bd0d-0a4d99ef2464", "Stir cooked rice, green onions, soy sauce, and black pepper in the same skillet until the rice is hot. In a separate skillet over medium heat, melt butter and gently fry eggs, turning once, until the yolks are still slightly runny but the egg whites are firm, about 3 minutes per egg."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/vegerice%2Fvege3.jpg?alt=media&token=47b86384-f0de-406d-bbe1-42796c838ff7", "To serve, divide hot cooked rice mixture between 3 serving bowls and top each bowl with 1/3 of the vegetable mixture and a fried egg. Serve sweet red chili sauce on the side for mixing into bibimbap."]], details: "This is vegetarian but there are many bibimbap recipes with beef or chicken marinades, if you want to add beef or chicken to this dish.")

let puffwaffles = Recipe(id: 17, name: "Puff Pastry Waffles", category: "traditional", preparationArray: [cookpastry], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/waffle%2Fwaffle.jpg?alt=media&token=3486a533-2de7-4205-9085-91d9e79c146d", price: 4, cookTime: 10, tag:["breakfast"], ingredients: ["frozen puff pastry" : ["1", "box"], "cooking spray": ["1", "bottle"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/waffle%2Funpackwaffle.jpg?alt=media&token=e07a0133-4deb-431f-bd64-4f141c14730e", "Line a cutting board with parchment paper. Unfold puff pastry onto cutting board. Cut each sheet into 4 equal squares."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/waffle%2Fspray.jpg?alt=media&token=9381ef5a-b474-4cd0-926b-a32feb12327e", "Preheat a waffle iron according to manufacturer's instructions. Grease with cooking spray."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/waffle%2Fcookpuff.jpg?alt=media&token=c5a0d3fb-2615-43a8-bc6b-2a9979fea741", "Place one puff pastry square in the preheated waffle iron; cook until golden brown, 3 to 5 minutes. Repeat with remaining puff pastry squares."]], details: "Add puff pastry to the list of good things you can snackify in your waffle iron. Although they don't puff up as much as oven-baked puff pastry, they turn out crispy on the outside and tender on the inside, and they take only minutes to make. Serve hot or at room temperature with syrup, fruit, Nutella®, fruit preserves, or nut butter.")

let potatosalad = Recipe(id: 18, name: "Southern Dill Potato Salad", category: "traditional", preparationArray: [cutPotato, chopOnion, cutcelery], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/potatosalad%2Fpotatosalad.jpg?alt=media&token=6414dae8-44bd-460f-bfcc-c84c26abadad", price: 10, cookTime: 10, tag:["lunch", "dinner", "low fat", "vegetarian"], ingredients: ["red potatos": ["5", "pounds"], "boiled eggs": ["5", "piece"], "sour cream": ["1", "cup"], "mayonnaise": ["1", "cup"], "white onion": ["1", "piece"], "celery": ["1", "stack"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/potatosalad%2Fboilpotato.jpg?alt=media&token=676310b6-f30a-4b91-bb4f-5308f98873ef", "Place the potatoes in a large pot, cover them with water, and bring to a boil over high heat. Reduce the heat to medium-low, and simmer until the potatoes are cooked through but still firm, about 20 minutes. Remove from the water, let cool, and cut the potatoes into chunks. Set the potatoes aside."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/potatosalad%2Fcream.jpg?alt=media&token=548e9396-50a0-4787-a6f1-1b67cf7a50cd", "In a bowl, stir together the sour cream, mayonnaise, apple cider vinegar, Dijon mustard, onion, celery, celery salt, and salt and pepper until well mixed."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/potatosalad%2Finbowl.jpg?alt=media&token=6c2ce805-a006-4d29-9367-c18d1ecefd6c", "Place the potatoes and eggs in a large salad bowl, and sprinkle with dried dill. Pour the dressing over the potatoes and eggs, and mix lightly. Cover and refrigerate the salad for at least 30 minutes. Serve cold."]], details: "Re-created potato-salad with a slight modern tangy twist. I know you will like it! Best taste is achieved when the salad is covered and placed in refrigerator overnight.")

let sandwich = Recipe(id: 19, name: "Philly Cheesesteak Sandwich with Garlic Mayo", category: "traditional", preparationArray: [cutcelery, cutpepper, sliceBeef], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/sandwich%2Fsandwich.jpg?alt=media&token=eeafcc98-a892-4641-bbd9-2a5ff7e383af", price: 10, cookTime: 20, tag: ["breakfast", "lunch", "dinner"], ingredients: ["mayonnaise": ["1", "cup"], "garlic" : ["2", "cloves"], "beef" : ["1", "pound"], "green bell pepper": ["2", "piece"], "hoagie rolls": ["4", "piece"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/potatosalad%2Fcream.jpg?alt=media&token=548e9396-50a0-4787-a6f1-1b67cf7a50cd", "In a small bowl, combine mayonnaise and minced garlic. Cover, and refrigerate."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/sandwich%2Fsautebeef.jpg?alt=media&token=e352a56d-a860-4559-90e4-800ed80d7d15", "Heat oil in a large skillet over medium heat. Saute beef until lightly browned. Stir in green pepper and onion, and season with salt and pepper. Saute until vegetables are tender, and remove from heat."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/sandwich%2Fspreadsauce.jpg?alt=media&token=45c6d252-45c7-4681-8e8b-6e0339ec08d5", "Spread each bun generously with garlic mayonnaise. Divide beef mixture into the buns. Top with shredded cheese, and sprinkle with oregano. Place sandwiches on a baking pan."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/sandwich%2Fheatsandwich.jpg?alt=media&token=66170d49-2298-4646-932f-7c54ca7b3da1", "Heat sandwiches in preheated oven, until cheese is melted or slightly browned."]], details: "This is a delicious and easy sandwich that gets rave reviews from my husband and brother. The garlic mayo is both easy and delicious.")

let couscousSalad = Recipe(id: 20, name: "Black Bean and Couscous Salad", category: "european", preparationArray: [cutchicken, chopOnion], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cousalad%2Fcouscoasalad.jpg?alt=media&token=f64efa9e-5492-45a1-add5-cadc497cea8a", price: 15, cookTime: 20, tag: ["lunch", "dinner", "low fat"], ingredients: ["couscous": ["1", "lb"], "chicken both": ["1", "lb"], "onion": ["8", "piece"], "bell pepper": ["1", "pieve"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cousalad%2Fsautecoco.jpg?alt=media&token=6b3068dc-e544-4b54-b7d0-af1a12d3af38", "Bring chicken broth to a boil in a 2 quart or larger sauce pan and stir in the couscous. Cover the pot and remove from heat. Let stand for 5 minutes."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cousalad%2Fpourcoca.jpg?alt=media&token=03d03ab0-ddf2-47f2-90df-c3b8ffd173b7", "In a large bowl, whisk together the olive oil, lime juice, vinegar and cumin. Add green onions, red pepper, cilantro, corn and beans and toss to coat."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/cousalad%2Fmixsalad.png?alt=media&token=34f90f83-eca1-4a30-be8b-71698949fdae", "Fluff the couscous well, breaking up any chunks. Add to the bowl with the vegetables and mix well. Season with salt and pepper to taste and serve at once or refrigerate until ready to serve."]], details: "This is a great salad for a lunch, with interesting textures and southwest flavors combined in one delicious salad. Leftovers store well refrigerated for several days.")

let chickenblue = Recipe(id: 21, name: "Chicken Cordon Bleu", category: "european", preparationArray: [cutchicken], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/chickenblue%2Fblue.jpg?alt=media&token=7193675e-c3a7-4b2a-85b6-3f0219a6ab1d", price: 25, cookTime: 20, tag: ["lunch", "dinner"], ingredients: ["chicken breast": ["6", "pieces"], "ham" : ["6", "pieces"], "cheese" : ["6", "slices"], "butter": ["3", "tsp"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/chickenblue%2Fplaceham.jpg?alt=media&token=4c538af5-51a1-4eab-af47-bf252eaab52f", "Pound chicken breasts if they are too thick. Place a cheese and ham slice on each breast within 1/2 inch of the edges. Fold the edges of the chicken over the filling, and secure with toothpicks. Mix the flour and paprika in a small bowl, and coat the chicken pieces."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/chickenblue%2Fheatbutter.jpg?alt=media&token=bafc2af1-f958-458d-8e59-e6ed3befd979", "Heat the butter in a large skillet over medium-high heat, and cook the chicken until browned on all sides. Add the wine and bouillon. Reduce heat to low, cover, and simmer for 30 minutes, until chicken is no longer pink and juices run clear."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/chickenblue%2Ffinal.jpg?alt=media&token=c6f6a34a-e5c0-4223-9e28-46bfd33f59a6", "Remove the toothpicks, and transfer the breasts to a warm platter. Blend the cornstarch with the cream in a small bowl, and whisk slowly into the skillet. Cook, stirring until thickened, and pour over the chicken. Serve warm."]], details: "Cordon Bleu' is a French term, literally translated as 'blue ribbon', that originally referred to an award for culinary excellence given to women cooks! The term can now apply to any superior cook (yes, men too), and also to this dish (chicken, ham and Swiss cheese slices, breaded and sauteed). This yummy version adds paprika and a creamy white wine sauce worthy of its own blue ribbon. Two blue ribbon tastes in wedded bliss -- Chicken Cordon Bleu II!")

let greekpasta = Recipe(id: 22, name: "Greek Chicken Pasta", category: "european", preparationArray: [cutchicken, chopOnion, cutGarlic], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greekpasta%2Fgreekpasta.jpg?alt=media&token=2bdf71a6-d60a-4c74-b825-2d8699bb81f0", price: 15, cookTime: 20, tag: ["lunch", "dinner"], ingredients: ["linguine pasta": ["16", "ounce"], "onion": ["1", "piece"], "chicken breast": ["1", "lb"], "tomato": ["2", "pieces"], "lemon": ["2", "piece"]], steps:[["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greekpasta%2Fboilpasta.jpg?alt=media&token=d629967d-92fa-432c-be05-bfafba0c8d6e", "Bring a large pot of lightly salted water to a boil. Cook pasta in boiling water until tender yet firm to the bit, 8 to 10 minutes; drain."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greekpasta%2F2.jpg?alt=media&token=ceaf0a8c-b0af-46d2-bacf-170bd6c7a106", "Heat olive oil in a large skillet over medium-high heat. Add onion and garlic; saute until fragrant, about 2 minutes. Stir in the chicken and cook, stirring occasionally, until chicken is no longer pink in the center and the juices run clear, about 5 to 6 minutes."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/greekpasta%2F3.jpg?alt=media&token=942357f8-fde1-4298-873e-f6352418fe97", "Reduce heat to medium-low; add artichoke hearts, tomato, feta cheese, parsley, lemon juice, oregano, and cooked pasta. Cook and stir until heated through, about 2 to 3 minutes. Remove from heat, season with salt and pepper, and garnish with lemon wedges."]], details: "This pasta dish incorporates some of the flavors of Greece. It makes a wonderfully complete and satisfying meal. For extra flavor, toss in a few kalamata olives. Use whatever pasta you have or prefer.")

let italianSoup = Recipe (id: 19, name: "Italian Sausage Soup with Tortellini", category: "european", preparationArray: [cutGarlic, peelCarrot, chopOnion, cutPotato, chopCabbage, cutSausage], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/italiansoup%2FitalianSoup.jpg?alt=media&token=537a80d9-d7b6-4720-837a-e4e3bb967f5a", price: 7, cookTime: 14, tag: ["lunch", "dinner", "low fat", "breakfast"], ingredients: ["potatoes" : ["10", "ounces"], "onions": ["1", " pieces"], "garlic": ["2", "pieces"], "sausage": ["1", "pound"], "Zucchini": ["2", "pieces"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/italiansoup%2FItaliansoup1.jpeg?alt=media&token=6fe30a1e-1c88-453f-a4d0-e0c7baec3931", "In a 5 quart Dutch oven, brown sausage. Remove sausage and drain, reserving 1 tablespoon of the drippings."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/italiansoup%2Fitaliansoup2.jpg?alt=media&token=a0a29f18-8865-4be9-81da-7c3e0ccf2e81","Saute onions and garlic in drippings. Stir in beef broth, water, wine, tomatoes, carrots, basil, oregano, tomato sauce, and sausage. Bring to a boil. Reduce heat; simmer uncovered for 30 minutes."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/italiansoup%2Fitaliansoup3.jpg?alt=media&token=06534bb8-19ec-4c8f-9559-6deaf63334ab", "Skim fat from the soup. Stir in zucchini and parsley. Simmer covered for 30 minutes. Add tortellini during the last 10 minutes. Sprinkle with Parmesan cheese on top of each serving."]], details: "This soup embodies all the wonders of Italian cooking: Italian sausage, garlic, tomatoes and red wines. Serve with hot bread and salad for a delicious meal. Garnish with Parmesan cheese.")

let frenchCrep = Recipe (id: 20, name: "French Crepes", category: "european", preparationArray: [ chopOnion, beatEggs, bun], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/crep%2Fcreps.jpg?alt=media&token=428d2dcd-9ef9-4df0-8deb-78d0d3ae188d", price: 5, cookTime: 10, tag: ["lunch", "dinner", "low fat", "breakfast", "vegetarian"], ingredients: ["flour" : ["1", "cup"], "white sugar": ["1", " teaspoon"], "salt": ["1/4", "teaspoon"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/crep%2Fcrep1.jpg?alt=media&token=fe37c377-e3fe-4a17-9bca-9f872a6b2288", "Sift together flour, sugar and salt; set aside. In a large bowl, beat eggs and milk together with an electric mixer. Beat in flour mixture until smooth; stir in melted butter."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/crep%2Fcrep2.jpg?alt=media&token=6bdb8df6-0966-457b-b3da-3488cae59ca9","Heat a lightly oiled griddle or frying pan over medium high heat. Pour or scoop the batter onto the griddle, using approximately 2 tablespoons for each crepe. Tip and rotate pan to spread batter as thinly as possible. Brown on both sides and serve hot."]], details: "A good breakfast for weekends and even desserts. Serve rolled up and filled with jam or fruit and whipped cream.")

let burrito = Recipe (id: 21, name: "Delicious Black Bean Burritos", category: "traditional", preparationArray: [ chopOnion, beatEggs, bun, cutGarlic], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burrito%2Fburrito.jpg?alt=media&token=e224d288-5412-45ef-b9a1-15b2b46874c4", price: 9, cookTime: 15, tag: ["lunch", "dinner", "low fat", "breakfast", "vegetarian"], ingredients: ["flour tortillas" : ["2", "pieces"], "vegetable oil": ["2", " tablespoons"], "salt": ["1", "teaspoon"],"onion": ["1", "piece"],"garlic": ["1", "teaspoon"],"cream cheese": ["3", "ounces"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burrito%2Fburrito1.jpg?alt=media&token=1c17fe87-7432-4607-90fb-3d75f051b179", "Wrap tortillas in foil and place in oven heated to 350 degrees F (175 degrees C). Bake for 15 minutes or until heated through."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burrito%2Fburrito2.jpg?alt=media&token=9650b8fe-51d6-43e3-a145-2c2684568f37","Heat oil in a 10-inch skillet over medium heat. Place onion, bell pepper, garlic and jalapenos in skillet, cook for 2 minutes stirring occasionally. Pour beans into skillet, cook 3 minutes stirring."], ["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burrito%2Fburrito3.jpg?alt=media&token=7bfb79e7-820c-4ed0-95ec-731e77ecc803","Cut cream cheese into cubes and add to skillet with salt. Cook for 2 minutes stirring occasionally. Stir cilantro into mixture."]], details: "These burritos are soooo good, you'll want to have them every night.")

let tofu = Recipe (id: 22, name: "Korean Soft Tofu Stew (Soon Du Bu Jigae)", category: "asian fusion", preparationArray: [ chopOnion, beatEggs, bun, cutGarlic, chopBeans], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/tofu%2Ftofu.jpg?alt=media&token=dec7dccf-7e3d-4690-a110-ddb3627333ab", price: 12, cookTime: 20, tag: ["lunch", "dinner"], ingredients: ["Korean chile powder" : ["1", "teaspoon"], "vegetable oil": ["1", " tablespoon"], "egg": ["1", "piece"],"onion": ["1", "piece"],"garlic": ["1", "teaspoon"],"cream cheese": ["2", "ounces"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/tofu%2Ftofu1.jpg?alt=media&token=8912a0d7-06d5-4fdc-a87f-f9bf12a89efd", "Heat the vegetable oil in a large saucepan over medium heat. Stir in the Korean chile powder and ground beef. Cook and stir until the beef is crumbly, evenly browned, and no longer pink. Stir in the soy bean paste, coating the beef. Pour in the water and bring to a boil. Season with salt and pepper. Gently drop tofu into the soup and continue cooking until the tofu is heated through, 1 to 2 minutes. Remove from heat and quickly add the egg into the soup, stirring gently to break it up. Garnish with sesame seeds and green onion."]], details: "This is an easy and authentic version of Korean tofu stew, used to eat this every day at a very popular restaurant. It's very versatile. Small pieces of meat or seafood can be added. It's thick and great in the winter and can be made very mild or very spicy.")

let burger = Recipe (id: 23, name: "Tex-Mex Burger with Cajun Mayo", category: "traditional", preparationArray: [ chopOnion, beatEggs, bun, cutGarlic, chopBeans, sliceBeef, trimBroccoli], imageName: "https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burger%2Fburger.jpg?alt=media&token=fafff39d-4f92-46d0-9382-276a2d2890b5", price: 12, cookTime: 20, tag: ["lunch", "dinner"], ingredients: ["Cajun seasoning" : ["1", "teaspoon"], "ground beef": ["1", " pound"], "egg": ["1", "piece"],"onion": ["1", "piece"],"garlic": ["1", "teaspoon"],"cream cheese": ["2", "ounces"],"lettuce": ["2", "pieces"]], steps: [["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burger%2Fburger1.jpg?alt=media&token=c46e76a4-2dbb-4c35-ae2f-9ab43541b754", "Preheat grill for medium-high heat. In a small bowl, mix together the mayonnaise and 1 teaspoon of Cajun seasoning. Set aside."],["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burger%2Fburger2.JPG?alt=media&token=1551cab9-de88-4574-8887-1d91eae79333", "In a large bowl, mix together the ground sirloin, jalapeno pepper, onion, garlic, 1 tablespoon Cajun seasoning, and Worcestershire sauce using your hands. Divide into 4 balls, and flatten into patties."],["https://firebasestorage.googleapis.com/v0/b/bundle-d5733.appspot.com/o/burger%2Fburger3.jpg?alt=media&token=723b4a32-93a1-4a7d-9b0e-8adef5a8880a", "Lightly oil the grilling surface, and place the patties on the grill. Cook for about 5 minutes per side, or until well done. During the last 2 minutes, lay a slice of cheese on top of each patty. Spread the seasoned mayonnaise onto the insides of the buns. Put burgers in the buns, and top with lettuce and tomato to serve."]], details: "A jazzy way to spice up the boring basic burger that will tantalize your taste buds! Cajun spiced mayonnaise is the perfect complement to these spicy beef burgers.")


